<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net10.0-windows10.0.19041.0;net10.0-android<!--;net10.0-ios;net10.0-maccatalyst--></TargetFrameworks>
		<AssemblyName>Plugin.BLE</AssemblyName>
		<RootNamespace>Plugin.BLE</RootNamespace>
		<Product>$(AssemblyName) ($(TargetFramework))</Product>
		<PackOnBuild>true</PackOnBuild>
		<PackageIcon>icon_small.png</PackageIcon>
		<NeutralLanguage>en</NeutralLanguage>
		<LangVersion>latest</LangVersion>
		<DefineConstants>$(DefineConstants);</DefineConstants>
	</PropertyGroup>

	<PropertyGroup>
		<SupportedOSPlatformVersion Condition="$(TargetFramework.Contains('-windows'))">10.0.19041.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$(TargetFramework.Contains('-windows'))">10.0.19041.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$(TargetFramework.Contains('-android'))">29.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$(TargetFramework.Contains('-ios'))">18.7</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$(TargetFramework.Contains('-maccatalyst'))">13.1</SupportedOSPlatformVersion>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)'=='Debug' ">
		<DebugSymbols>true</DebugSymbols>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
	</PropertyGroup>
	
	<ItemGroup>
		<None Include="..\..\icon_small.png" Pack="true" Visible="false" PackagePath="" />
	</ItemGroup>

	<!-- Shared -->
	<ItemGroup>
		<Folder Include="Shared\" />
	</ItemGroup>

	<!-- Windows -->
	<ItemGroup Condition="$(TargetFramework.Contains('-windows')) != true">
		<Compile Remove="**\*.Windows.cs" />
		<None Include="**\*.Windows.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
		<Compile Remove="**\Windows\**\*.cs" />
		<None Include="**\Windows\**\*.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
	</ItemGroup>

	<!-- Android -->
	<ItemGroup Condition="$(TargetFramework.StartsWith('net10.0-android')) != true">
		<Compile Remove="**\*.Android.cs" />
		<None Include="**\*.Android.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
		<Compile Remove="**\Android\**\*.cs" />
		<None Include="**\Android\**\*.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
	</ItemGroup>

	<!-- iOS + Mac Catalyst (Apple folder) -->
	<ItemGroup Condition="!$(TargetFramework.StartsWith('net10.0-ios')) AND !$(TargetFramework.StartsWith('net10.0-maccatalyst'))">
		<Compile Remove="**\*.Apple.cs" />
		<None Include="**\*.Apple.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
		<Compile Remove="**\Apple\**\*.cs" />
		<None Include="**\Apple\**\*.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
	</ItemGroup>

</Project>
